import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dataDir = path.join(root, "data");

const headers = [
  "company",
  "website",
  "city_hub",
  "segment",
  "what_they_make",
  "e1_producer",
  "e2_accessible",
  "revenue_estimate_inr_cr",
  "revenue_basis",
  "c3_differentiation",
  "c4_decision_maker",
  "c5_growing_sector",
  "c6_growth_signals",
  "c7_systems_maturity",
  "c8_leadership_succession",
  "federer_score",
  "band",
  "growth_signals_observed",
  "systems_evidence",
  "decision_maker_or_succession_notes",
  "personalization_hook",
  "source_urls",
  "caveats_next_verification",
];

const rows = [
  {
    company: "Divgi TorqTransfer Systems Ltd",
    website: "https://divgi-tts.com/",
    city_hub: "Pune / Bhosari",
    segment: "Precision auto components & engineering",
    what_they_make: "Torque transfer systems, transfer cases, dual-clutch transmission modules and EV transmission solutions for OEMs.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 219,
    revenue_basis: "FY25 annual revenue about Rs 219Cr; TTM about Rs 303Cr.",
    c3_differentiation: 20,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 15,
    growth_signals_observed: "TTM growth; EV drivetrain focus; current quarterly-results page; public-company governance.",
    systems_evidence: "Listed company controls, OEM-quality drivetrain manufacturing, annual reports and structured investor reporting.",
    decision_maker_or_succession_notes: "Professional board and specialist leadership depth; promoter/family legacy visible but operating roles are distributed.",
    personalization_hook: "Your Bhosari team sits at an unusually sharp intersection: legacy torque-transfer know-how and the EV transmission shift that most auto suppliers are still trying to interpret.",
    source_urls: "https://divgi-tts.com/quarterly-results/ | https://stockanalysis.com/quote/nse/DIVGIITTS/revenue/ | https://divgi-tts.com/wp-content/uploads/2025/08/DTTS_AnnualReport_Finalsubmission_signed_FY2024-25.pdf",
    caveats_next_verification: "Confirm latest FY26 annual revenue after final audited results; still below 500Cr on FY25 and TTM sources used here.",
  },
  {
    company: "Kalyani Forge Ltd",
    website: "https://kalyaniforge.com/",
    city_hub: "Pune",
    segment: "Precision auto components & engineering",
    what_they_make: "Forged and machined components for passenger vehicles, CVs, turbochargers, industrial and agro-engine applications.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 237,
    revenue_basis: "FY25 sales about Rs 236.64Cr.",
    c3_differentiation: 20,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 15,
    growth_signals_observed: "Annual report references commissioning/expansion work; FY25 public filings; sector mix includes EV-agnostic and industrial portfolios.",
    systems_evidence: "IATF 16949, ISO 9001 and OEM operating systems referenced in annual-report material; digital operations mentioned in FY24/FY25 materials.",
    decision_maker_or_succession_notes: "Board/professional governance with Kalyani-family industrial depth; leadership beyond one founder.",
    personalization_hook: "I noticed Kalyani Forge is deliberately pushing beyond conventional auto forgings into industrial and EV-agnostic components, which makes your operating cadence more complex than a normal forging shop.",
    source_urls: "https://kalyaniforge.com/investors/annual-reports/ | https://www.etmoney.com/stocks/kalyani-forge-ltd/financials/3644/ | https://kalyaniforge.com/wp-content/uploads/2025/01/Annual-Report-2024.pdf",
    caveats_next_verification: "Use the latest annual report for final FY25 system-language quotations before submission.",
  },
  {
    company: "Simmonds Marshall Ltd",
    website: "https://www.simmondsmarshall.com/",
    city_hub: "Pune / Chakan",
    segment: "Precision auto components & engineering",
    what_they_make: "Specialised automotive fasteners, bolts, studs and cold-forged components.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 230,
    revenue_basis: "Quarterly FY26 run-rate roughly Rs 54-66Cr per quarter; FY25 operating revenue in mid-200Cr range.",
    c3_differentiation: 20,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 15,
    growth_signals_observed: "FY26 quarterly revenue growth; CARE rating coverage; current BSE/public filings.",
    systems_evidence: "IATF 16949, ISO 9001, ISO 14001 and management-system references in BSE/CARE documents.",
    decision_maker_or_succession_notes: "Listed governance with professional controls and board/KMP structure.",
    personalization_hook: "Your Chakan operation is not selling generic fasteners; the IATF-backed cold-forged product mix makes Simmonds Marshall a quiet process-discipline story inside the auto supply chain.",
    source_urls: "https://groww.in/stocks/simmonds-marshall-ltd/company-financial | https://www.careratings.com/upload/CompanyFiles/PR/202603120304_Simmonds_Marshall_Limited.pdf | https://bsmedia.business-standard.com/_media/bs/data/announcements/bse/30082025/97725d25-10d6-427e-b66b-c1a4ff034445.pdf",
    caveats_next_verification: "Pull audited FY25 annual report directly from BSE/NSE before final outreach.",
  },
  {
    company: "Walchandnagar Industries Ltd",
    website: "https://walchand.com/",
    city_hub: "Pune / Walchandnagar industrial belt",
    segment: "Precision engineering",
    what_they_make: "High-complexity equipment and components for nuclear, aerospace, missile, defence, gears and industrial products.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 259,
    revenue_basis: "FY25 annual revenue about Rs 259Cr; TTM about Rs 235Cr.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 7.5,
    c7_systems_maturity: 20,
    c8_leadership_succession: 15,
    growth_signals_observed: "Q3 FY26 turnaround; defence/nuclear/aerospace tailwinds; current investor releases.",
    systems_evidence: "ISO 9001:2015, ASME/IBR/API/AGMA-style quality systems, in-house NDT, CNC/precision infrastructure and listed-company controls.",
    decision_maker_or_succession_notes: "Listed professional management and independent governance; not dependent on one promoter operator.",
    personalization_hook: "Your Walchandnagar facility has the kind of mixed nuclear, aerospace and gear workload where execution rhythm is as strategic as engineering capability.",
    source_urls: "https://walchand.com/about-us/manufacturing-infrastructure/ | https://stockanalysis.com/quote/nse/WALCHANNAG/revenue/ | https://walchand.com/wp-content/uploads/2025/07/Walchannagard%20AR%202025%20Full%20PDF%20file%20R2.pdf",
    caveats_next_verification: "Operational hub is Pune district/near-Pune rather than central Pune; include justification in methodology.",
  },
  {
    company: "Duroshox Pvt Ltd",
    website: "https://duroshox.com/",
    city_hub: "Pune / Sanaswadi",
    segment: "Precision auto components & engineering",
    what_they_make: "Shock absorbers, damping systems, vibration isolation, motion-control and suspension assemblies for OEMs.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 309,
    revenue_basis: "Estimated annual revenue about USD 37M, about Rs 309Cr.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "Employee growth; global OEM customers; active 2025 technical articles; India-US hybrid manufacturing model.",
    systems_evidence: "Lean manufacturing, CAD/FEA/CAE, prototyping, validation, ISO/TS references, quality systems and zero-PPM case evidence.",
    decision_maker_or_succession_notes: "Leadership appears professional/founder-led; succession depth should be checked via MCA/LinkedIn.",
    personalization_hook: "Your custom damping work for off-highway and industrial OEMs looks like a full-stack engineering operation, not a catalogue shock-absorber business.",
    source_urls: "https://duroshox.com/products/ | https://growjo.com/company/Duroshox_Private_Limited | https://duroshox.com/how-hybrid-manufacturing-and-full-stack-engineering-are-powering-high-quality-low-cost-production/",
    caveats_next_verification: "Revenue is third-party estimate; verify with MCA/Tofler before final scoring.",
  },
  {
    company: "Nichrome India Ltd",
    website: "https://www.nichrome.com/",
    city_hub: "Pune / Shirwal",
    segment: "Precision engineering",
    what_they_make: "Integrated packaging machines and automated packaging systems for food, pharma, personal-care, agrochemical and industrial applications.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 125,
    revenue_basis: "Tofler revenue band Rs 100-150Cr, FY25 basis.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 7.5,
    c7_systems_maturity: 10,
    c8_leadership_succession: 15,
    growth_signals_observed: "Current website, exports to 50+ countries, 11,000+ installations, strong packaging automation tailwinds.",
    systems_evidence: "Manufacturing and solution design infrastructure; export network; system maturity inferred from global installations and machine lifecycle support.",
    decision_maker_or_succession_notes: "Founder-generation and next-generation leadership visible: S.V. Joshi and Mrunal Joshi as CEO/Vice Chairperson.",
    personalization_hook: "Nichrome’s move from India’s first milk pouch machine to integrated packaging automation gives you a rare founder-led systems story to tell customers.",
    source_urls: "https://www.nichrome.com/about/ | https://www.tofler.in/nichrome-india-limited/company/U28113MH1960PLC011575 | https://economictimes.indiatimes.com/industry/cons-products/food/nichrome-india-eyes-20-per-cent-revenue-growth-for-next-5-years/articleshow/27748214.cms",
    caveats_next_verification: "Factory is Shirwal, near Pune; include as Pune district/near-hub operations.",
  },
  {
    company: "Electro Pneumatics & Hydraulics (India) Pvt Ltd",
    website: "https://www.electropneumatics.com/",
    city_hub: "Pune / Chakan",
    segment: "Precision engineering",
    what_they_make: "Hydraulic presses, tube benders, servo-mechanical presses, hydroforming systems, fluid-power products and defence trawl assemblies.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 140,
    revenue_basis: "Historical net sales around Rs 137Cr; current assets and credit coverage imply mid-sized scale.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "CARE coverage; 2026 defence order; revenue growth in FY24; multiple current job openings.",
    systems_evidence: "Structured machine divisions, CARE-rated bank facilities, annual business planning in job postings, project planning and software/mechanical/hydraulic integration.",
    decision_maker_or_succession_notes: "Promoter/professional leadership includes Ashley Rasquinha, Ingrid Rasquinha and Prashant Gadepalli.",
    personalization_hook: "Your Chakan business is balancing machine manufacturing, fluid-power components and defence assemblies, which is exactly where structured execution discipline compounds quickly.",
    source_urls: "https://www.thecompanycheck.com/company/electro-pneumatics-and-hydraulics-india-pvt-ltd/U28932PN1983PTC190794 | https://www.tofler.in/electro-pneumatics-and-hydraulics-india-pvt-ltd/company/U28932PN1983PTC190794 | https://www.careratings.com/upload/CompanyFiles/PR/202603120347_Electro_Pneumatics_And_Hydraulics_%28India%29_Private_Limited.pdf",
    caveats_next_verification: "Use latest CARE PDF for exact FY25/FY26 revenue if available.",
  },
  {
    company: "Electronica HiTech Machine Tools Pvt Ltd",
    website: "https://www.electronicahitech.com/",
    city_hub: "Pune",
    segment: "Precision engineering",
    what_they_make: "Metal cutting, metal forming, CNC, EDM, VMC and related machine-tool solutions.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 90,
    revenue_basis: "Tofler revenue band Rs 75-100Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 15,
    growth_signals_observed: "FY24 revenue growth, FY25 filings, active products and IMTMA-style machine-tool tailwinds.",
    systems_evidence: "Formal MCA filings; industrial machine-tool production; moderate systems evidence through manufacturing scale and compliance.",
    decision_maker_or_succession_notes: "Managing Director Sujit Natekar with directors Mugdha Kaskhediker and Shilpa Pophale.",
    personalization_hook: "Electronica HiTech’s Rs 75-100Cr machine-tool business has the exact complexity where production planning and after-sales feedback can become a strategic edge.",
    source_urls: "https://www.tofler.in/electronica-hitech-machine-tools-private-limited/company/U29210PN2011PTC139073 | https://www.thecompanycheck.com/company/electronica-hitech-machine-tools-private-limited/U29210PN2011PTC139073 | https://www.electronicahitech.net/",
    caveats_next_verification: "Some product lines include sourced/import machines; confirm manufacturing share during final qualification call.",
  },
  {
    company: "Electronica Mechatronic Systems (India) Pvt Ltd",
    website: "https://www.electronicaems.com/",
    city_hub: "Pune",
    segment: "Industrial sensors & instrumentation",
    what_they_make: "Optical encoders, metrology systems, coordinate measuring machines, height gauges and special-purpose inspection machines.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 203,
    revenue_basis: "Estimated annual revenue about USD 24.4M, about Rs 203Cr.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 15,
    growth_signals_observed: "FY24 revenue growth; 2025 filings; in-house R&D and defence/rail/medical manufacturing customers.",
    systems_evidence: "Govt-approved R&D setup, in-house encoders/metrology manufacturing, structured inspection-machine capability.",
    decision_maker_or_succession_notes: "Managing Director Radhika Madgulkar and director Mohan Madgulkar show leadership depth.",
    personalization_hook: "Your shift from indigenous encoders into CMMs and inspection SPMs shows a rare Pune instrumentation company building its own product ladder.",
    source_urls: "https://www.electronicaems.com/about-us | https://growjo.com/company/Electronica_Mechatronic_Systems_India_Pvt. | https://www.thecompanycheck.com/company/electronica-mechatronic-systems-india-private-limited/U31403MH1986PTC040814",
    caveats_next_verification: "Revenue is third-party estimate; verify exact band with MCA/Tofler.",
  },
  {
    company: "Accurate Gauging & Instruments Pvt Ltd",
    website: "https://www.accurategauging.com/",
    city_hub: "Pune",
    segment: "Industrial sensors & instrumentation",
    what_they_make: "3D coordinate measuring machines, measuring instruments, calibration, inspection and contract assembly.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 125,
    revenue_basis: "Tofler revenue band Rs 100-150Cr, FY25 basis.",
    c3_differentiation: 20,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "FY24 revenue growth, FY25 filings, metrology tailwinds from quality-driven manufacturing.",
    systems_evidence: "Metrology/calibration services require structured quality processes; MCA filings and manufacturing scale support moderate systems maturity.",
    decision_maker_or_succession_notes: "Leadership depth to be verified; not a solo-trader profile.",
    personalization_hook: "Accurate Gauging looks like a metrology partner that helps manufacturers build discipline into quality itself, not just buy inspection equipment.",
    source_urls: "https://www.tofler.in/accurate-gauging-and-instruments-pvt-ltd/company/U33125MH1987PTC042232 | https://www.thecompanycheck.com/company/electronica-hitech-machine-tools-private-limited/U29210PN2011PTC139073",
    caveats_next_verification: "Confirm latest certification list and whether CMM assembly is fully in-house versus partner assembly.",
  },
  {
    company: "Poona Forge Pvt Ltd",
    website: "https://poonaforge.com/",
    city_hub: "Pune / Bhosari",
    segment: "Precision auto components & engineering",
    what_they_make: "Forged components for automotive, engineering and agricultural applications.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 175,
    revenue_basis: "Tofler revenue band Rs 150-200Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 7.5,
    c7_systems_maturity: 10,
    c8_leadership_succession: 15,
    growth_signals_observed: "FY25 filings; 10% revenue growth; Bhosari manufacturing presence.",
    systems_evidence: "Formal filings, manufacturing scale and forged-component process controls; ERP evidence not yet explicit.",
    decision_maker_or_succession_notes: "Javalekar family leadership spans Anil, Sanjevani and Chinmay Javalekar.",
    personalization_hook: "Poona Forge’s Bhosari forged-component base has enough product variety across auto, engineering and agro to make execution visibility a real lever.",
    source_urls: "https://www.tofler.in/poona-forge-pvt-ltd/company/U28910MH1979PTC021262 | https://www.thecompanycheck.com/company/poona-forge-pvt-ltd/U28910MH1979PTC021262",
    caveats_next_verification: "Need direct website/certification capture before final founder outreach.",
  },
  {
    company: "Polybond (India) Pvt Ltd",
    website: "https://polybond.co.in/",
    city_hub: "Pune",
    segment: "Precision auto components & engineering",
    what_they_make: "Rubber parts and rubber-to-metal bonded parts for automotive and industrial applications.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 175,
    revenue_basis: "Tofler revenue band Rs 100-500Cr, FY24 basis; row normalized to mid-band.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "FY24 EBITDA and net-worth growth; auto/industrial rubber tailwinds.",
    systems_evidence: "Manufacturing scale and process-intensive rubber bonding; explicit ERP evidence not yet found.",
    decision_maker_or_succession_notes: "Rathi-family leadership visible; succession depth needs LinkedIn/MCA confirmation.",
    personalization_hook: "Rubber-to-metal bonding is a process business where tiny quality deviations travel straight into OEM pain, so Polybond’s execution system is part of the product.",
    source_urls: "https://www.tofler.in/polybond-india-pvt-ltd/company/U25199MH1983PTC030558",
    caveats_next_verification: "Revenue band is broad; confirm exact sales and certifications.",
  },
  {
    company: "Dyna-K Automotive Stampings Pvt Ltd",
    website: "http://www.dynakstamp.com/",
    city_hub: "Pune / Bhosari",
    segment: "Precision auto components & engineering",
    what_they_make: "Brake components, welded assemblies and turbocharger-related components/services.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 125,
    revenue_basis: "Tofler revenue band Rs 100-150Cr, FY24 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "FY24 revenue and EBITDA growth; active filings; Bhosari plant.",
    systems_evidence: "Auto-component manufacturing and welding process controls; explicit ERP/system proof not yet public.",
    decision_maker_or_succession_notes: "Leadership depth to verify; active private-company governance.",
    personalization_hook: "Dyna-K’s mix of brake components, welded assemblies and turbocharger work suggests a plant where scheduling and quality discipline decide the margin.",
    source_urls: "https://www.tofler.in/dyna-k-automotive-stampings-private-limited/company/U28910PN1985PTC038409",
    caveats_next_verification: "Because bulk stamping can be commodity, verify proportion of precision/turbocharger work before final inclusion.",
  },
  {
    company: "Solidus Hi-Tech Product Pvt Ltd",
    website: "https://www.solidushitech.com/",
    city_hub: "Pune / Bhosari",
    segment: "Precision auto components & engineering",
    what_they_make: "Automotive sheet-metal components, busbars, industrial enclosures, storage systems and related fabrication products.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 175,
    revenue_basis: "Tofler revenue band Rs 100-500Cr, FY24 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "FY24 revenue, EBITDA and asset growth; busbars benefit from electrification tailwinds.",
    systems_evidence: "Sheet-metal fabrication and busbar manufacturing at scale; explicit ERP evidence to verify.",
    decision_maker_or_succession_notes: "Musale-family leadership visible across directors.",
    personalization_hook: "Your busbar and enclosure work places Solidus closer to electrification infrastructure than a normal sheet-metal fabricator.",
    source_urls: "https://www.tofler.in/solidus-hi-tech-product-private-limited/company/U31200PN2004PTC019656",
    caveats_next_verification: "Check customer concentration and whether automotive/busbar revenue is the core, not only storage/consumer products.",
  },
  {
    company: "Kinetic Communications Ltd",
    website: "https://kcl.kineticindia.com/",
    city_hub: "Pune / Chinchwad",
    segment: "Precision auto components & engineering",
    what_they_make: "EV motor controller units, power and driver board assemblies, telecom/electronics assemblies and controller box assemblies.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 125,
    revenue_basis: "Tofler revenue band Rs 100-150Cr, FY25 basis.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 15,
    growth_signals_observed: "Fully automated EV controller line inaugurated July 2025; 180,000-unit annual output; FY25 revenue band.",
    systems_evidence: "SMT lines, 100% verification, PLC/HMI-controlled line, software flashing, IP67 leak testing and functional validation.",
    decision_maker_or_succession_notes: "Firodia next-generation leadership and director Deepak Shikarpur visible in launch sources.",
    personalization_hook: "Your new automated MCU line in Chinchwad is an ideal example of a mid-sized company turning EV electronics into an operating-system challenge.",
    source_urls: "https://www.theweek.in/wire-updates/business/2025/07/01/dcm82-biz-kinetic-communications.html | https://www.tofler.in/kinetic-communications-limited/company/U74999MH1995PTC089588 | https://auto.economictimes.indiatimes.com/amp/news/auto-components/kinetic-communications-inaugurates-automated-ev-component-manufacturing-line-in-pune/122181243",
    caveats_next_verification: "Confirm whether KCL is majority held within the promoter group and not externally controlled.",
  },
  {
    company: "Kinetic Engineering Ltd",
    website: "https://kineticindia.com/",
    city_hub: "Pune / Chinchwad decision hub with Ahilyanagar plant",
    segment: "Precision auto components & engineering",
    what_they_make: "Automotive components, gears, shafts, chassis lines and EV-related component/battery initiatives.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 142,
    revenue_basis: "FY25 operating income about Rs 142Cr; TTM about Rs 151Cr.",
    c3_differentiation: 10,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 15,
    growth_signals_observed: "EV battery plant, automated/robotic chassis line, promoter infusion and revenue target communications.",
    systems_evidence: "IoT-enabled battery facility, automated assembly lines, stage-wise inspections and listed-company controls.",
    decision_maker_or_succession_notes: "Arun Firodia and Ajinkya Firodia indicate clear generational succession depth.",
    personalization_hook: "Kinetic’s shift from legacy auto components into EV batteries, controllers and robotic chassis manufacturing creates exactly the cross-functional execution load founders struggle to see in dashboards.",
    source_urls: "https://stockanalysis.com/quote/bom/500240/revenue/ | https://www.crisil.com/mnt/winshare/Ratings/RatingList/RatingDocs/KineticEngineeringLimited_August%2019_%202025_RR_376367.html | https://www.autocarpro.in/news/kinetic-group-to-manufacture-ev-batteries-at-new-ahmednagar-facility-125053",
    caveats_next_verification: "Manufacturing plant is Ahilyanagar, while Pune/Chinchwad is the decision hub; keep only if DeepThought accepts city-hub logic.",
  },
  {
    company: "CEM Electromech Pvt Ltd",
    website: "",
    city_hub: "Pune",
    segment: "Industrial sensors & instrumentation / precision electronics",
    what_they_make: "Electrical and electromechanical components for industrial applications.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 125,
    revenue_basis: "Tofler revenue band Rs 100-150Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 7.5,
    c7_systems_maturity: 10,
    c8_leadership_succession: 15,
    growth_signals_observed: "FY25 filings; FY24/FY25 manufacturing scale; electrical components benefit from industrial electrification.",
    systems_evidence: "Manufacturing scale and MCA compliance; detailed ERP/process evidence not public.",
    decision_maker_or_succession_notes: "Three-director leadership with Sunil Gupta, Salonee Gupta and Narayanan P. Iyer.",
    personalization_hook: "CEM Electromech’s Rs 100-150Cr electrical-component scale looks like the point where founder memory stops being enough and operating data starts mattering.",
    source_urls: "https://www.tofler.in/cem-electromech-private-limited/company/U31900PN2011PTC140308",
    caveats_next_verification: "Needs official website/product-depth verification; include as B-probable rather than A.",
  },
  {
    company: "Takshi Auto Components Pvt Ltd",
    website: "",
    city_hub: "Pune",
    segment: "Precision auto components & engineering",
    what_they_make: "Automotive components including axle assemblies and flange accessories.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 350,
    revenue_basis: "Tofler revenue band Rs 300-400Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "Revenue and EBITDA growth; active filings; large auto-component scale.",
    systems_evidence: "Auto-component manufacturing at Rs 300-400Cr scale implies formal quality/process systems; explicit ERP evidence still required.",
    decision_maker_or_succession_notes: "Director/professional depth to be checked.",
    personalization_hook: "Takshi’s axle and flange assembly business is the kind of supplier operation where dispatch discipline, quality loops and working-capital visibility all collide.",
    source_urls: "https://www.tofler.in/takshi-auto-components-private-limited/company/U34300PN2003PTC017771",
    caveats_next_verification: "Need official website and certification evidence before final outreach.",
  },
  {
    company: "Chasys Automotive Components Pvt Ltd",
    website: "",
    city_hub: "Pune",
    segment: "Precision auto components & engineering",
    what_they_make: "Automotive components including auto parts, gas kits and rubber parts.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 175,
    revenue_basis: "Tofler revenue band Rs 150-200Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "20% revenue growth and major EBITDA improvement in FY24/FY25 source data.",
    systems_evidence: "Mid-sized auto-component production; explicit ERP/IATF proof not yet located.",
    decision_maker_or_succession_notes: "Leadership depth to verify.",
    personalization_hook: "Chasys looks to be in the uncomfortable but valuable zone: enough auto-component volume to need process discipline, but still small enough for the founder team to change it quickly.",
    source_urls: "https://www.tofler.in/chasys-automotive-components-private-limited/company/U29197PN2009PTC135208",
    caveats_next_verification: "Check if products are differentiated enough; may be B-minus if commodity mix dominates.",
  },
  {
    company: "Accu-Sharp Cutting Tools Pvt Ltd",
    website: "",
    city_hub: "Pune",
    segment: "Precision engineering",
    what_they_make: "Industrial cutting tools and precision tooling for machining applications.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 60,
    revenue_basis: "Tofler revenue band Rs 50-75Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "FY25 revenue band; revenue growth; cutting-tool demand from machining and Make-in-India capex.",
    systems_evidence: "Precision tooling production requires measured quality controls; ERP evidence not yet public.",
    decision_maker_or_succession_notes: "Leadership depth to verify.",
    personalization_hook: "Cutting tools are small parts with outsized uptime impact, so Accu-Sharp’s operating discipline can become visible in every customer’s machining cell.",
    source_urls: "https://www.tofler.in/accu-sharp-cutting-tools-private-limited/company/U28990PN2011PTC140118",
    caveats_next_verification: "Need official product/certification confirmation; treat as B-probable.",
  },
  {
    company: "Sawalka Tools and Machines Pvt Ltd",
    website: "",
    city_hub: "Pune / Chakan",
    segment: "Precision auto components & engineering",
    what_they_make: "U-bolts, radius rods, torsion bars, stabilizer bars, tie bars and related automotive suspension components.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 60,
    revenue_basis: "Tofler revenue band Rs 50-75Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "Revenue growth; Chakan location; auto suspension component tailwinds.",
    systems_evidence: "Auto suspension tooling/components require QA/process discipline; explicit ERP evidence not yet located.",
    decision_maker_or_succession_notes: "Multiple directors indicate leadership depth.",
    personalization_hook: "Sawalka’s torsion-bar and stabilizer-bar work sits close to vehicle ride-quality outcomes, which makes shop-floor repeatability a sales argument.",
    source_urls: "https://www.tofler.in/sawalka-tools-and-machines-private-limited/company/U99999MH1985PTC070692",
    caveats_next_verification: "Need direct website/customer/certification proof.",
  },
  {
    company: "Pentagon Assembly Automation Pvt Ltd",
    website: "https://www.pentagonassemblyautomation.com/",
    city_hub: "Pune",
    segment: "Precision engineering",
    what_they_make: "Assembly automation, special-purpose machines and production-line automation systems.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 60,
    revenue_basis: "Tofler revenue band Rs 50-75Cr, FY23/FY25 source basis.",
    c3_differentiation: 20,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "Automation sector tailwinds; high custom-project nature; active private-company filings.",
    systems_evidence: "Automation builders require project planning, controls engineering and commissioning systems; explicit ERP evidence not yet public.",
    decision_maker_or_succession_notes: "Leadership depth to verify from LinkedIn/MCA.",
    personalization_hook: "Pentagon is building the systems other manufacturers use to run better, which makes your own internal execution system especially interesting.",
    source_urls: "https://www.tofler.in/pentagon-assembly-automation-private-limited/company/U29299PN2006PTC128866",
    caveats_next_verification: "Need latest FY25 filing and customer examples before final outreach.",
  },
  {
    company: "Labindia Instruments Pvt Ltd",
    website: "https://www.labindia.com/",
    city_hub: "Pune",
    segment: "Industrial sensors & instrumentation",
    what_they_make: "Analytical, laboratory and process instruments with sales, service and instrumentation expertise.",
    e1_producer: "PASS - specialized instrumentation/service; manufacturing share to verify",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 175,
    revenue_basis: "Tofler revenue band Rs 150-200Cr, FY25 basis.",
    c3_differentiation: 10,
    c4_decision_maker: 7.5,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "Revenue and EBITDA growth; lab/instrumentation tailwinds in pharma, biotech and QA.",
    systems_evidence: "Instrumentation service network and regulated-lab customer base suggest structured support systems; ERP evidence not public.",
    decision_maker_or_succession_notes: "Four-director leadership; professional depth visible.",
    personalization_hook: "Labindia’s instrument business likely sees customer process pain every day, which is a useful entry point for talking about internal execution data.",
    source_urls: "https://www.tofler.in/labindia-instruments-pvt-ltd/company/U33125MH1982PTC027977 | https://www.labindia.com/",
    caveats_next_verification: "Must verify E1 carefully: if primarily distributor/service partner, move to fail list.",
  },
  {
    company: "Fluid Controls Ltd",
    website: "https://fluidcontrols.com/",
    city_hub: "Pune / Chakan",
    segment: "Industrial sensors & instrumentation",
    what_they_make: "Instrumentation fittings, valves, manifolds, pre-fabricated instrument hook-ups, high-pressure needle valves and rail/nuclear/oil-and-gas flow-control hardware.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 175,
    revenue_basis: "Tofler revenue band Rs 150-200Cr, FY25 basis; Growjo estimate about USD 24.4M.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 15,
    c7_systems_maturity: 20,
    c8_leadership_succession: 15,
    growth_signals_observed: "Employee growth; DSIR-recognized R&D; rail/nuclear/oil-and-gas approvals; active 2026 company overview.",
    systems_evidence: "DSIR in-house R&D, ISO 9001/14001/OHSAS, PED, ASTM, API fire-safe, cryogenic/fugitive-emission and ABS PDA certifications.",
    decision_maker_or_succession_notes: "Founder Dr Y.E. Moochhala plus BU heads and professional managers visible.",
    personalization_hook: "Your Chakan R&D-and-manufacturing setup for rail, nuclear and oil-and-gas instrumentation hardware is exactly the kind of technical operation where process visibility wins trust.",
    source_urls: "https://www.tofler.in/fluid-controls-pvt-ltd/company/U29120PN1981PLC232367 | https://growjo.com/company/Fluid_Controls_Private_Limited | https://fluidcontrols.com/wp-content/uploads/2026/02/Company-overview-new-2026.pdf",
    caveats_next_verification: "Head office is Mumbai but manufacturing/R&D is in Chakan, Pune; document this explicitly.",
  },
  {
    company: "Minilec Protective Relay Pvt Ltd / Minilec Group",
    website: "https://minilecgroup.com/",
    city_hub: "Pune / Pirangut",
    segment: "Industrial sensors & instrumentation",
    what_they_make: "Motor and pump protection relays, phase-failure relays, alarm annunciators, event-monitoring systems and industrial protection/control electronics.",
    e1_producer: "PASS",
    e2_accessible: "PASS",
    revenue_estimate_inr_cr: 55,
    revenue_basis: "Revenue not directly public for manufacturing entity; employee base, charges and group scale indicate probable Rs 50Cr+; verify MCA.",
    c3_differentiation: 20,
    c4_decision_maker: 15,
    c5_growing_sector: 15,
    c6_growth_signals: 7.5,
    c7_systems_maturity: 10,
    c8_leadership_succession: 7.5,
    growth_signals_observed: "Exports to 40-45+ countries; 2025 filings; 60+ years operations; new product launches.",
    systems_evidence: "In-house design/development, high-tech testing lab, IEC/CE compliance testing, 40,000 sq ft manufacturing plant.",
    decision_maker_or_succession_notes: "Technocrat founder Yashavant Ghaisas and multiple directors; succession depth needs verification.",
    personalization_hook: "Minilec’s home-grown protection relay line has the feel of an Indian product company that had to build both engineering discipline and channel discipline over decades.",
    source_urls: "https://minilecgroup.com/about-us/ | https://www.engnetglobal.com/c/f.aspx/MIN022 | https://www.thecompanycheck.com/company/minilec-protective-relay-pvt-ltd/U31909PN1985PTC036283",
    caveats_next_verification: "Revenue is the weakest evidence point in the final 25; replace with Krohne/WIKA only if DeepThought permits MNC/JV subsidiaries.",
  },
];

function band(score) {
  if (score >= 80) return "A - Strong Federer";
  if (score >= 60) return "B - Probable Federer";
  if (score >= 40) return "C - Borderline";
  return "D - Not ICP";
}

for (const row of rows) {
  row.federer_score = [
    row.c3_differentiation,
    row.c4_decision_maker,
    row.c5_growing_sector,
    row.c6_growth_signals,
    row.c7_systems_maturity,
    row.c8_leadership_succession,
  ].reduce((a, b) => a + b, 0);
  row.band = band(row.federer_score);
}

const auditHeaders = ["company", "reason_rejected_or_deferred", "source_or_note"];
const auditRows = [
  ["Bharat Forge Ltd", "Revenue far above Rs 500Cr; large group flagship.", "FY25 consolidated revenue Rs 15,123Cr in annual report."],
  ["Forbes Marshall", "Likely above target revenue band and large established group.", "Pune instrumentation/process-control leader, but not mid-sized Federer target."],
  ["Praj Industries", "Revenue far above target band.", "FY25 revenue above Rs 3,000Cr in public filings."],
  ["Thermax Ltd", "Revenue far above target band.", "Large listed Pune engineering group."],
  ["Kirloskar Pneumatic", "Revenue above target band and large group context.", "Pune industrial machinery company."],
  ["Varroc Engineering", "Revenue far above target band.", "Large auto components group."],
  ["Endurance Technologies", "Revenue far above target band.", "Large auto components group."],
  ["NIBE Ltd", "FY25 revenue crossed about Rs 507Cr, just over cutoff; high volatility.", "StockAnalysis / Equitymaster FY25 data."],
  ["Indo Schottle / SFS Group India", "Strong technical fit but now part of Switzerland-based SFS Group; large-group subsidiary caveat.", "IATF/AS9100 certifications and Pune plant evidence."],
  ["Krohne Marshall Pvt Ltd", "Revenue and Pune instrumentation fit, but JV/MNC/Forbes Marshall group control makes Federer fit weaker.", "Tofler revenue band Rs 300-400Cr."],
  ["WIKA Instruments India", "Foreign subsidiary; revenue at/near Rs 500Cr.", "Tofler revenue band around Rs 500Cr."],
  ["Nord Drivesystems India", "Foreign subsidiary.", "Tofler revenue band Rs 300-400Cr."],
  ["Vishay Components India", "Foreign subsidiary.", "Tofler revenue band Rs 300-400Cr."],
  ["Benteler Automotive India", "Foreign subsidiary.", "Tofler revenue band Rs 100-500Cr."],
  ["ElringKlinger Automotive Components India", "Foreign subsidiary.", "Tofler revenue band Rs 200-300Cr."],
  ["Manas Microsystems", "Baumer Group company; subsidiary caveat.", "Pune flowmeter manufacturer."],
  ["Tronsoft Technologies", "Trader/wholesaler-distributor; fails E1 producer gate.", "IndiaMART profile says trader/wholesaler."],
  ["Duro Technical Systems", "Distribution arm, not producer; producer is Duroshox.", "Official site says exclusive distributor."],
  ["Jayashree Electron", "Excellent product fit but revenue evidence suggests below Rs 50Cr; deferred.", "eleB2B turnover Rs 250mn; CompanyCheck growth only."],
  ["Protocontrol Instruments", "Product fit, but revenue/scale appears too small; deferred.", "CompanyCheck/Tofler revenue not available and small charge base."],
  ["Technofour Electronics", "Strong instrument fit but part of METTLER TOLEDO; subsidiary caveat.", "Official site says part of METTLER TOLEDO."],
  ["KSH International", "Likely above target band after IPO scale; verify before considering.", "IPO note indicates large borrowings and major expansion."],
];

function csvEscape(value) {
  if (value === null || value === undefined) return "";
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function toCsv(cols, records) {
  const lines = [cols.map(csvEscape).join(",")];
  for (const record of records) {
    const row = Array.isArray(record) ? record : cols.map((col) => record[col]);
    lines.push(row.map(csvEscape).join(","));
  }
  return `${lines.join("\n")}\n`;
}

await fs.mkdir(dataDir, { recursive: true });
const pipelineCsv = toCsv(headers, rows);
const auditCsv = toCsv(auditHeaders, auditRows);
await fs.writeFile(path.join(dataDir, "federer_companies_pune.csv"), pipelineCsv, "utf8");
await fs.writeFile(path.join(dataDir, "candidate_audit_log.csv"), auditCsv, "utf8");

const summary = {
  generated_at: new Date().toISOString(),
  scope: {
    city_hub: "Pune operational hub: Chakan, Bhosari, Pimpri-Chinchwad, Sanaswadi, Pirangut and nearby Pune industrial belt",
    segments: ["Industrial sensors & instrumentation", "Precision auto components & engineering"],
  },
  counts: {
    final_companies: rows.length,
    audit_rejections_or_deferrals: auditRows.length,
    band_a: rows.filter((r) => r.band.startsWith("A")).length,
    band_b: rows.filter((r) => r.band.startsWith("B")).length,
    band_c: rows.filter((r) => r.band.startsWith("C")).length,
  },
  cautions: [
    "Private-company revenue ranges should be re-checked through MCA/Tofler/EMIS before outreach.",
    "Minilec is retained as probable Federer because product and operations fit is strong, but revenue proof is weaker than the other 24.",
    "Kinetic Engineering is retained because Pune is the decision hub, but the main manufacturing facility is outside Pune in Ahilyanagar.",
  ],
};
await fs.writeFile(path.join(dataDir, "score_summary.json"), JSON.stringify(summary, null, 2), "utf8");

const workbook = Workbook.create();
const pipeline = workbook.worksheets.add("Federer Pipeline");
pipeline.getRange(`A1:${String.fromCharCode(64 + headers.length)}1`).values = [headers];
pipeline.getRange(`A2:${String.fromCharCode(64 + headers.length)}${rows.length + 1}`).values =
  rows.map((row) => headers.map((header) => row[header] ?? ""));

const audit = workbook.worksheets.add("Audit Log");
audit.getRange("A1:C1").values = [auditHeaders];
audit.getRange(`A2:C${auditRows.length + 1}`).values = auditRows;

const summarySheet = workbook.worksheets.add("Summary");
summarySheet.getRange("A1:B12").values = [
  ["Scope", summary.scope.city_hub],
  ["Segments", summary.scope.segments.join(" + ")],
  ["Final companies", summary.counts.final_companies],
  ["Audit rejects/deferred", summary.counts.audit_rejections_or_deferrals],
  ["Band A", summary.counts.band_a],
  ["Band B", summary.counts.band_b],
  ["Band C", summary.counts.band_c],
  ["Caution 1", summary.cautions[0]],
  ["Caution 2", summary.cautions[1]],
  ["Caution 3", summary.cautions[2]],
  ["Scoring", "C3 20 + C4 15 + C5 15 + C6 15 + C7 20 + C8 15 = 100"],
  ["Prepared for", "Souradeep Ghosh"],
];

const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(path.join(dataDir, "federer_companies_pune.xlsx"));

console.log(JSON.stringify(summary, null, 2));
